### API Documentation for Contact Management System
### BASE URL    
### http://localhost:10000/contacts
### https://cse341-project1-1-test.onrender.com/contacts    
### This API allows you to manage contacts, including creating, reading, updating, and deleting contacts.
### API Endpoints

### Get all users
GET http://localhost:10000/users


### Get contact by ID
GET http://localhost:10000/users/681edf918616d9a9d1cd0ec9/


### Create a new contact
POST http://localhost:10000/users HTTP/1.1
Content-Type: application/json

{
  "firstName": "Ned Stark",
  "lastName": "Sean",
  "email": "sean_bean@gameofthron.es",
  "favoriteColor": "req.body.password",
  "birthday": "09-18/2000"
}


### Update a contact
PUT http://localhost:10000/users/68322097443a1fdd341ff382
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "jane.doe@example.com",
  "favoriteColor":,
  "birthday":
}



### Delete a contact
DELETE http://localhost:10000/users/1

