### API Documentation for Contact Management System
### BASE URL    
### http://localhost:10000/contacts
### https://cse341-project1-1-test.onrender.com/contacts    
### This API allows you to manage contacts, including creating, reading, updating, and deleting contacts.
### API Endpoints

### Get all users
GET https://cse341-project1-62aw.onrender.com/users


### Get contact by ID
GET https://cse341-project1-62aw.onrender.com/users/681edf918616d9a9d1cd0ec9/


### Create a new contact
POST https://cse341-project1-62aw.onrender.com/users HTTP/1.1
Content-Type: application/json

{
  "name":"Ned Stark",
  "email":"sean_bean@gameofthron.es",
  "password":"$2b$12$UREFwsRUoyF0CRqGNK0LzO0HM/jLhgUCNNIJ9RJAqMUQ74crlJ1Vu"
}


### Update a contact
PUT https://cse341-project1-62aw.onrender.com/users/1
Content-Type: application/json

{
  "firstName": "Jane Doe",
  "lastName":"Jean",
  "email": "",
}


### Delete a contact
DELETE https://cse341-project1-62aw.onrender.com/users/1
